apiVersion: batch/v1beta1
kind: CronJob # This tells kubernetes what kind of class it is working with
metadata:
  name: minion-gpu
spec:
  schedule: "*/30 * * * *" # every hour
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          hostNetwork: true # This option will allow the pod to use the host network for internet access
          containers:
          - name: minion-gpu
            image: ninai/pipeline:tf-gpu
            imagePullPolicy: Always  # needed because the image tag is not latest
            volumeMounts:
            - name: mnt
              mountPath: /mnt
            resources:
              limits:
                nvidia.com/gpu: 1
            env:
            - name: DJ_HOST
              valueFrom:
                secretKeyRef:
                  name: dj-login
                  key: DJ_HOST
            - name: DJ_USER
              valueFrom:
                secretKeyRef:
                  name: dj-login
                  key: DJ_USER
            - name: DJ_PASS
              valueFrom:
                secretKeyRef:
                  name: dj-login
                  key: DJ_PASS
            command: ["/bin/bash"]
            args: ["-c", "python3 /data/pipeline/python/scripts/populate-minion_gpu.py"]
          imagePullSecrets:  # to pull private images
            - name: docker-login
          volumes:
          - name: mnt
            hostPath:
              path: /mnt
          tolerations:
          - key: "gpu"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          affinity: # Place this in the pod.spec level in the yaml file
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: gpu_mem_size
                    operator: In
                    values: # You can remove certain mem_size if your code need more memory
                    - 11GB
                    - 12GB
                    - 24GB
